<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>BDVM.Dispatch</AssemblyName>
    <RootNamespace>BDVM.Dispatch</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Integration\**\*.cs" />
    <ProjectReference Include="..\BDVM.Common\BDVM.Common.csproj" />
    <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
